services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./rental-service/server/API/Dockerfile
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: frontend-app
    build:
      # Указываем контекст в папку фронтенда
      context: ./rental-service/client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: