server {
    listen 80;
    server_name localhost;
    client_max_body_size 50M;

    # 1. Раздача фронтенда (React)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Нужно для React Router (SPA)
    }

    # 2. Проксирование запросов к API
    location /api/ {
        # 'api' — это имя сервиса из docker-compose.yaml
        proxy_pass http://api:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 3. Проксирование запросов к статическим файлам (аватары и т.д.)
    location /static/ {
        proxy_pass http://api:8080/static/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
