name: Auto Deploy to Server

on:
  push:
    branches: [ main, master, backend/lab1, nodejs ]  # при пуше в эти ветки

jobs:
  deploy:
    # Используем наш self-hosted runner
    runs-on: self-hosted
    # Если добавляли метки, можно уточнить:
    # runs-on: [self-hosted, prod, docker]

    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # 2. Деплой через Docker Compose
      - name: Deploy with Docker Compose
        run: |
          # Переходим в домашнюю папку (или создаём проектную)
          cd ~
          
          # Создаём папку для проекта, если её нет
          mkdir -p ~/app
          
          # Копируем docker-compose.yml из репозитория
          rsync -av --delete --exclude='.git' ${{ github.workspace }}/ ~/app/
          
          # Копируем папку с приложением (если собираете локально)
          # или просто переходим в папку проекта
          cd ~/app
          
          # Останавливаем старые контейнеры
          docker compose down || true
          
          # Собираем и запускаем заново
          docker compose up -d --build
          
          docker image prune -f
          
          # Проверяем статус
          docker compose ps
          